/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class AdminUsersListRequest {
    /**
     * Set `cursor` to `next_cursor` returned by the previous call to list items in the next page.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=cursor")
    public String cursor;

    public AdminUsersListRequest withCursor(String cursor) {
        this.cursor = cursor;
        return this;
    }
    
    /**
     * Limit for how many users to be retrieved per page
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")
    public Long limit;

    public AdminUsersListRequest withLimit(Long limit) {
        this.limit = limit;
        return this;
    }
    
    /**
     * The ID (`T1234`) of the workspace.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=team_id")
    public String teamId;

    public AdminUsersListRequest withTeamId(String teamId) {
        this.teamId = teamId;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `admin.users:read`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;

    public AdminUsersListRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public AdminUsersListRequest(@JsonProperty("team_id") String teamId, @JsonProperty("token") String token) {
        this.teamId = teamId;
        this.token = token;
  }
}
