/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class AdminConversationsRenameRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public AdminConversationsRenameApplicationJSON requestBody;
    public AdminConversationsRenameRequest withRequestBody(AdminConversationsRenameApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `admin.conversations:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;
    public AdminConversationsRenameRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public AdminConversationsRenameRequest(@JsonProperty("RequestBody") AdminConversationsRenameApplicationJSON requestBody, @JsonProperty("token") String token) {
        this.requestBody = requestBody;
        this.token = token;
  }
}
