/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class AdminUsersAssignApplicationJSON {
    /**
     * Comma separated values of channel IDs to add user in the new workspace.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("channel_ids")
    public String channelIds;
    public AdminUsersAssignApplicationJSON withChannelIds(String channelIds) {
        this.channelIds = channelIds;
        return this;
    }
    
    /**
     * True if user should be added to the workspace as a guest.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_restricted")
    public Boolean isRestricted;
    public AdminUsersAssignApplicationJSON withIsRestricted(Boolean isRestricted) {
        this.isRestricted = isRestricted;
        return this;
    }
    
    /**
     * True if user should be added to the workspace as a single-channel guest.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_ultra_restricted")
    public Boolean isUltraRestricted;
    public AdminUsersAssignApplicationJSON withIsUltraRestricted(Boolean isUltraRestricted) {
        this.isUltraRestricted = isUltraRestricted;
        return this;
    }
    
    /**
     * The ID (`T1234`) of the workspace.
     */
    @JsonProperty("team_id")
    public String teamId;
    public AdminUsersAssignApplicationJSON withTeamId(String teamId) {
        this.teamId = teamId;
        return this;
    }
    
    /**
     * The ID of the user to add to the workspace.
     */
    @JsonProperty("user_id")
    public String userId;
    public AdminUsersAssignApplicationJSON withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public AdminUsersAssignApplicationJSON(@JsonProperty("team_id") String teamId, @JsonProperty("user_id") String userId) {
        this.teamId = teamId;
        this.userId = userId;
  }
}
