/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class AdminConversationsConvertToPrivateResponse {
    
    public String contentType;
    public AdminConversationsConvertToPrivateResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public AdminConversationsConvertToPrivateResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public AdminConversationsConvertToPrivateResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> adminConversationsConvertToPrivateErrorSchema;
    public AdminConversationsConvertToPrivateResponse withAdminConversationsConvertToPrivateErrorSchema(java.util.Map<String, java.util.Map<String, Object>> adminConversationsConvertToPrivateErrorSchema) {
        this.adminConversationsConvertToPrivateErrorSchema = adminConversationsConvertToPrivateErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> adminConversationsConvertToPrivateSchema;
    public AdminConversationsConvertToPrivateResponse withAdminConversationsConvertToPrivateSchema(java.util.Map<String, java.util.Map<String, Object>> adminConversationsConvertToPrivateSchema) {
        this.adminConversationsConvertToPrivateSchema = adminConversationsConvertToPrivateSchema;
        return this;
    }
    
    public AdminConversationsConvertToPrivateResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
