/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class AdminConversationsCreateResponse {
    
    public String contentType;

    public AdminConversationsCreateResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public AdminConversationsCreateResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public AdminConversationsCreateResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> adminConversationsCreateErrorSchema;

    public AdminConversationsCreateResponse withAdminConversationsCreateErrorSchema(java.util.Map<String, java.util.Map<String, Object>> adminConversationsCreateErrorSchema) {
        this.adminConversationsCreateErrorSchema = adminConversationsCreateErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> adminConversationsCreateSchema;

    public AdminConversationsCreateResponse withAdminConversationsCreateSchema(java.util.Map<String, java.util.Map<String, Object>> adminConversationsCreateSchema) {
        this.adminConversationsCreateSchema = adminConversationsCreateSchema;
        return this;
    }
    
    public AdminConversationsCreateResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
