/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class AdminConversationsArchiveRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public AdminConversationsArchiveApplicationJSON requestBody;
    public AdminConversationsArchiveRequest withRequestBody(AdminConversationsArchiveApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `admin.conversations:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;
    public AdminConversationsArchiveRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public AdminConversationsArchiveRequest(@JsonProperty("RequestBody") AdminConversationsArchiveApplicationJSON requestBody, @JsonProperty("token") String token) {
        this.requestBody = requestBody;
        this.token = token;
  }
}
