/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class AdminEmojiRemoveRequestBody {
    /**
     * The name of the emoji to be removed. Colons (`:myemoji:`) around the value are not required, although they may be included.
     */
    @SpeakeasyMetadata("form:name=name")
    public String name;

    public AdminEmojiRemoveRequestBody withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `admin.teams:write`
     */
    @SpeakeasyMetadata("form:name=token")
    public String token;

    public AdminEmojiRemoveRequestBody withToken(String token) {
        this.token = token;
        return this;
    }
    
    public AdminEmojiRemoveRequestBody(@JsonProperty("name") String name, @JsonProperty("token") String token) {
        this.name = name;
        this.token = token;
  }
}
