/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class AdminConversationsConvertToPrivateRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public AdminConversationsConvertToPrivateApplicationJSON requestBody;
    public AdminConversationsConvertToPrivateRequest withRequestBody(AdminConversationsConvertToPrivateApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `admin.conversations:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;
    public AdminConversationsConvertToPrivateRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public AdminConversationsConvertToPrivateRequest(@JsonProperty("RequestBody") AdminConversationsConvertToPrivateApplicationJSON requestBody, @JsonProperty("token") String token) {
        this.requestBody = requestBody;
        this.token = token;
  }
}
