/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class AdminAppsApproveRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public AdminAppsApproveApplicationJSON requestBody;

    public AdminAppsApproveRequest withRequestBody(AdminAppsApproveApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `admin.apps:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;

    public AdminAppsApproveRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public AdminAppsApproveRequest(@JsonProperty("token") String token) {
        this.token = token;
  }
}
