/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class AdminConversationsUnarchiveApplicationJSON {
    /**
     * The channel to unarchive.
     */
    @JsonProperty("channel_id")
    public String channelId;
    public AdminConversationsUnarchiveApplicationJSON withChannelId(String channelId) {
        this.channelId = channelId;
        return this;
    }
    
    public AdminConversationsUnarchiveApplicationJSON(@JsonProperty("channel_id") String channelId) {
        this.channelId = channelId;
  }
}
