/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class AdminTeamsSettingsSetIconRequestBody {
    /**
     * Image URL for the icon
     */
    @SpeakeasyMetadata("form:name=image_url")
    public String imageUrl;

    public AdminTeamsSettingsSetIconRequestBody withImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
        return this;
    }
    
    /**
     * ID for the workspace to set the icon for.
     */
    @SpeakeasyMetadata("form:name=team_id")
    public String teamId;

    public AdminTeamsSettingsSetIconRequestBody withTeamId(String teamId) {
        this.teamId = teamId;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `admin.teams:write`
     */
    @SpeakeasyMetadata("form:name=token")
    public String token;

    public AdminTeamsSettingsSetIconRequestBody withToken(String token) {
        this.token = token;
        return this;
    }
    
    public AdminTeamsSettingsSetIconRequestBody(@JsonProperty("image_url") String imageUrl, @JsonProperty("team_id") String teamId, @JsonProperty("token") String token) {
        this.imageUrl = imageUrl;
        this.teamId = teamId;
        this.token = token;
  }
}
