/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class AdminConversationsDeleteResponse {
    
    public String contentType;
    public AdminConversationsDeleteResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public AdminConversationsDeleteResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public AdminConversationsDeleteResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> adminConversationsDeleteErrorSchema;
    public AdminConversationsDeleteResponse withAdminConversationsDeleteErrorSchema(java.util.Map<String, java.util.Map<String, Object>> adminConversationsDeleteErrorSchema) {
        this.adminConversationsDeleteErrorSchema = adminConversationsDeleteErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> adminConversationsDeleteSchema;
    public AdminConversationsDeleteResponse withAdminConversationsDeleteSchema(java.util.Map<String, java.util.Map<String, Object>> adminConversationsDeleteSchema) {
        this.adminConversationsDeleteSchema = adminConversationsDeleteSchema;
        return this;
    }
    
    public AdminConversationsDeleteResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
