/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class AdminTeamsSettingsInfoRequest {
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=team_id")
    public String teamId;

    public AdminTeamsSettingsInfoRequest withTeamId(String teamId) {
        this.teamId = teamId;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `admin.teams:read`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;

    public AdminTeamsSettingsInfoRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public AdminTeamsSettingsInfoRequest(@JsonProperty("team_id") String teamId, @JsonProperty("token") String token) {
        this.teamId = teamId;
        this.token = token;
  }
}
