/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class AdminConversationsGetConversationPrefsRequest {
    /**
     * The channel to get preferences for.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=channel_id")
    public String channelId;
    public AdminConversationsGetConversationPrefsRequest withChannelId(String channelId) {
        this.channelId = channelId;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `admin.conversations:read`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;
    public AdminConversationsGetConversationPrefsRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public AdminConversationsGetConversationPrefsRequest(@JsonProperty("channel_id") String channelId, @JsonProperty("token") String token) {
        this.channelId = channelId;
        this.token = token;
  }
}
