/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class AdminInviteRequestsApproveRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public AdminInviteRequestsApproveApplicationJSON requestBody;

    public AdminInviteRequestsApproveRequest withRequestBody(AdminInviteRequestsApproveApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `admin.invites:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;

    public AdminInviteRequestsApproveRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public AdminInviteRequestsApproveRequest(@JsonProperty("RequestBody") AdminInviteRequestsApproveApplicationJSON requestBody, @JsonProperty("token") String token) {
        this.requestBody = requestBody;
        this.token = token;
  }
}
