/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class AdminUsersSetAdminApplicationJSON {
    /**
     * The ID (`T1234`) of the workspace.
     */
    @JsonProperty("team_id")
    public String teamId;

    public AdminUsersSetAdminApplicationJSON withTeamId(String teamId) {
        this.teamId = teamId;
        return this;
    }
    
    /**
     * The ID of the user to designate as an admin.
     */
    @JsonProperty("user_id")
    public String userId;

    public AdminUsersSetAdminApplicationJSON withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public AdminUsersSetAdminApplicationJSON(@JsonProperty("team_id") String teamId, @JsonProperty("user_id") String userId) {
        this.teamId = teamId;
        this.userId = userId;
  }
}
