/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class AdminTeamsCreateApplicationJSON {
    /**
     * Description for the team.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("team_description")
    public String teamDescription;

    public AdminTeamsCreateApplicationJSON withTeamDescription(String teamDescription) {
        this.teamDescription = teamDescription;
        return this;
    }
    
    /**
     * Who can join the team. A team's discoverability can be `open`, `closed`, `invite_only`, or `unlisted`.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("team_discoverability")
    public String teamDiscoverability;

    public AdminTeamsCreateApplicationJSON withTeamDiscoverability(String teamDiscoverability) {
        this.teamDiscoverability = teamDiscoverability;
        return this;
    }
    
    /**
     * Team domain (for example, slacksoftballteam).
     */
    @JsonProperty("team_domain")
    public String teamDomain;

    public AdminTeamsCreateApplicationJSON withTeamDomain(String teamDomain) {
        this.teamDomain = teamDomain;
        return this;
    }
    
    /**
     * Team name (for example, Slack Softball Team).
     */
    @JsonProperty("team_name")
    public String teamName;

    public AdminTeamsCreateApplicationJSON withTeamName(String teamName) {
        this.teamName = teamName;
        return this;
    }
    
    public AdminTeamsCreateApplicationJSON(@JsonProperty("team_domain") String teamDomain, @JsonProperty("team_name") String teamName) {
        this.teamDomain = teamDomain;
        this.teamName = teamName;
  }
}
