/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class AdminUsersRemoveApplicationJSON {
    /**
     * The ID (`T1234`) of the workspace.
     */
    @JsonProperty("team_id")
    public String teamId;

    public AdminUsersRemoveApplicationJSON withTeamId(String teamId) {
        this.teamId = teamId;
        return this;
    }
    
    /**
     * The ID of the user to remove.
     */
    @JsonProperty("user_id")
    public String userId;

    public AdminUsersRemoveApplicationJSON withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public AdminUsersRemoveApplicationJSON(@JsonProperty("team_id") String teamId, @JsonProperty("user_id") String userId) {
        this.teamId = teamId;
        this.userId = userId;
  }
}
