/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class AdminUsergroupsRemoveChannelsRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public AdminUsergroupsRemoveChannelsApplicationJSON requestBody;
    public AdminUsergroupsRemoveChannelsRequest withRequestBody(AdminUsergroupsRemoveChannelsApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `admin.usergroups:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;
    public AdminUsergroupsRemoveChannelsRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public AdminUsergroupsRemoveChannelsRequest(@JsonProperty("RequestBody") AdminUsergroupsRemoveChannelsApplicationJSON requestBody, @JsonProperty("token") String token) {
        this.requestBody = requestBody;
        this.token = token;
  }
}
