/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class AdminConversationsGetTeamsRequest {
    /**
     * The channel to determine connected workspaces within the organization for.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=channel_id")
    public String channelId;

    public AdminConversationsGetTeamsRequest withChannelId(String channelId) {
        this.channelId = channelId;
        return this;
    }
    
    /**
     * Set `cursor` to `next_cursor` returned by the previous call to list items in the next page
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=cursor")
    public String cursor;

    public AdminConversationsGetTeamsRequest withCursor(String cursor) {
        this.cursor = cursor;
        return this;
    }
    
    /**
     * The maximum number of items to return. Must be between 1 - 1000 both inclusive.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")
    public Long limit;

    public AdminConversationsGetTeamsRequest withLimit(Long limit) {
        this.limit = limit;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `admin.conversations:read`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;

    public AdminConversationsGetTeamsRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public AdminConversationsGetTeamsRequest(@JsonProperty("channel_id") String channelId, @JsonProperty("token") String token) {
        this.channelId = channelId;
        this.token = token;
  }
}
