/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class AdminUsergroupsAddTeamsApplicationJSON {
    /**
     * When `true`, this method automatically creates new workspace accounts for the IDP group members.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("auto_provision")
    public Boolean autoProvision;
    public AdminUsergroupsAddTeamsApplicationJSON withAutoProvision(Boolean autoProvision) {
        this.autoProvision = autoProvision;
        return this;
    }
    
    /**
     * A comma separated list of encoded team (workspace) IDs. Each workspace *MUST* belong to the organization associated with the token.
     */
    @JsonProperty("team_ids")
    public String teamIds;
    public AdminUsergroupsAddTeamsApplicationJSON withTeamIds(String teamIds) {
        this.teamIds = teamIds;
        return this;
    }
    
    /**
     * An encoded usergroup (IDP Group) ID.
     */
    @JsonProperty("usergroup_id")
    public String usergroupId;
    public AdminUsergroupsAddTeamsApplicationJSON withUsergroupId(String usergroupId) {
        this.usergroupId = usergroupId;
        return this;
    }
    
    public AdminUsergroupsAddTeamsApplicationJSON(@JsonProperty("team_ids") String teamIds, @JsonProperty("usergroup_id") String usergroupId) {
        this.teamIds = teamIds;
        this.usergroupId = usergroupId;
  }
}
