/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class AdminUsersSetOwnerApplicationJSON {
    /**
     * The ID (`T1234`) of the workspace.
     */
    @JsonProperty("team_id")
    public String teamId;
    public AdminUsersSetOwnerApplicationJSON withTeamId(String teamId) {
        this.teamId = teamId;
        return this;
    }
    
    /**
     * Id of the user to promote to owner.
     */
    @JsonProperty("user_id")
    public String userId;
    public AdminUsersSetOwnerApplicationJSON withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public AdminUsersSetOwnerApplicationJSON(@JsonProperty("team_id") String teamId, @JsonProperty("user_id") String userId) {
        this.teamId = teamId;
        this.userId = userId;
  }
}
