/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class AdminTeamsCreateRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public AdminTeamsCreateApplicationJSON requestBody;

    public AdminTeamsCreateRequest withRequestBody(AdminTeamsCreateApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `admin.teams:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;

    public AdminTeamsCreateRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public AdminTeamsCreateRequest(@JsonProperty("RequestBody") AdminTeamsCreateApplicationJSON requestBody, @JsonProperty("token") String token) {
        this.requestBody = requestBody;
        this.token = token;
  }
}
