/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class AdminTeamsSettingsSetNameApplicationJSON {
    /**
     * The new name of the workspace.
     */
    @JsonProperty("name")
    public String name;

    public AdminTeamsSettingsSetNameApplicationJSON withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * ID for the workspace to set the name for.
     */
    @JsonProperty("team_id")
    public String teamId;

    public AdminTeamsSettingsSetNameApplicationJSON withTeamId(String teamId) {
        this.teamId = teamId;
        return this;
    }
    
    public AdminTeamsSettingsSetNameApplicationJSON(@JsonProperty("name") String name, @JsonProperty("team_id") String teamId) {
        this.name = name;
        this.teamId = teamId;
  }
}
