/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class AdminConversationsSearchResponse {
    
    public String contentType;

    public AdminConversationsSearchResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public AdminConversationsSearchResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public AdminConversationsSearchResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> adminConversationsSearchErrorSchema;

    public AdminConversationsSearchResponse withAdminConversationsSearchErrorSchema(java.util.Map<String, java.util.Map<String, Object>> adminConversationsSearchErrorSchema) {
        this.adminConversationsSearchErrorSchema = adminConversationsSearchErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> adminConversationsSearchSchema;

    public AdminConversationsSearchResponse withAdminConversationsSearchSchema(java.util.Map<String, java.util.Map<String, Object>> adminConversationsSearchSchema) {
        this.adminConversationsSearchSchema = adminConversationsSearchSchema;
        return this;
    }
    
    public AdminConversationsSearchResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
