/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class AppsPermissionsInfoRequest {
    /**
     * Authentication token. Requires scope: `none`
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=token")
    public String token;
    public AppsPermissionsInfoRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public AppsPermissionsInfoRequest(){}
}
