/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class AuthTestResponse {
    
    public String contentType;

    public AuthTestResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public AuthTestResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public AuthTestResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Standard failure response when used with an invalid token
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> authTestErrorSchema;

    public AuthTestResponse withAuthTestErrorSchema(java.util.Map<String, java.util.Map<String, Object>> authTestErrorSchema) {
        this.authTestErrorSchema = authTestErrorSchema;
        return this;
    }
    
    /**
     * Standard success response when used with a user token
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> authTestSuccessSchema;

    public AuthTestResponse withAuthTestSuccessSchema(java.util.Map<String, java.util.Map<String, Object>> authTestSuccessSchema) {
        this.authTestSuccessSchema = authTestSuccessSchema;
        return this;
    }
    
    public AuthTestResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
