/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class CallsUpdateApplicationJSON {
    /**
     * When supplied, available Slack clients will attempt to directly launch the 3rd-party Call with this URL.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("desktop_app_join_url")
    public String desktopAppJoinUrl;
    public CallsUpdateApplicationJSON withDesktopAppJoinUrl(String desktopAppJoinUrl) {
        this.desktopAppJoinUrl = desktopAppJoinUrl;
        return this;
    }
    
    /**
     * `id` returned by the [`calls.add`](/methods/calls.add) method.
     */
    @JsonProperty("id")
    public String id;
    public CallsUpdateApplicationJSON withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The URL required for a client to join the Call.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("join_url")
    public String joinUrl;
    public CallsUpdateApplicationJSON withJoinUrl(String joinUrl) {
        this.joinUrl = joinUrl;
        return this;
    }
    
    /**
     * The name of the Call.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("title")
    public String title;
    public CallsUpdateApplicationJSON withTitle(String title) {
        this.title = title;
        return this;
    }
    
    public CallsUpdateApplicationJSON(@JsonProperty("id") String id) {
        this.id = id;
  }
}
