/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ChatUnfurlResponse {
    
    public String contentType;
    public ChatUnfurlResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public ChatUnfurlResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public ChatUnfurlResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> chatUnfurlErrorSchema;
    public ChatUnfurlResponse withChatUnfurlErrorSchema(java.util.Map<String, java.util.Map<String, Object>> chatUnfurlErrorSchema) {
        this.chatUnfurlErrorSchema = chatUnfurlErrorSchema;
        return this;
    }
    
    /**
     * Typical, minimal success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> chatUnfurlSuccessSchema;
    public ChatUnfurlResponse withChatUnfurlSuccessSchema(java.util.Map<String, java.util.Map<String, Object>> chatUnfurlSuccessSchema) {
        this.chatUnfurlSuccessSchema = chatUnfurlSuccessSchema;
        return this;
    }
    
    public ChatUnfurlResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
