/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ChatGetPermalinkResponse {
    
    public String contentType;

    public ChatGetPermalinkResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public ChatGetPermalinkResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ChatGetPermalinkResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Error response when channel cannot be found
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> chatGetPermalinkErrorSchema;

    public ChatGetPermalinkResponse withChatGetPermalinkErrorSchema(java.util.Map<String, java.util.Map<String, Object>> chatGetPermalinkErrorSchema) {
        this.chatGetPermalinkErrorSchema = chatGetPermalinkErrorSchema;
        return this;
    }
    
    /**
     * Standard success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> chatGetPermalinkSuccessSchema;

    public ChatGetPermalinkResponse withChatGetPermalinkSuccessSchema(java.util.Map<String, java.util.Map<String, Object>> chatGetPermalinkSuccessSchema) {
        this.chatGetPermalinkSuccessSchema = chatGetPermalinkSuccessSchema;
        return this;
    }
    
    public ChatGetPermalinkResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
