/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class ChatMeMessageRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public ChatMeMessageApplicationJSON requestBody;
    public ChatMeMessageRequest withRequestBody(ChatMeMessageApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `chat:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;
    public ChatMeMessageRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public ChatMeMessageRequest(){}
}
