/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class ChatUpdateRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public ChatUpdateApplicationJSON requestBody;

    public ChatUpdateRequest withRequestBody(ChatUpdateApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `chat:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;

    public ChatUpdateRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public ChatUpdateRequest(@JsonProperty("RequestBody") ChatUpdateApplicationJSON requestBody, @JsonProperty("token") String token) {
        this.requestBody = requestBody;
        this.token = token;
  }
}
