/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ChatScheduleMessageResponse {
    
    public String contentType;
    public ChatScheduleMessageResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public ChatScheduleMessageResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public ChatScheduleMessageResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response if the `post_at` is invalid (ex. in the past or too far into the future)
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> chatScheduleMessageErrorSchema;
    public ChatScheduleMessageResponse withChatScheduleMessageErrorSchema(java.util.Map<String, java.util.Map<String, Object>> chatScheduleMessageErrorSchema) {
        this.chatScheduleMessageErrorSchema = chatScheduleMessageErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> chatScheduleMessageSuccessSchema;
    public ChatScheduleMessageResponse withChatScheduleMessageSuccessSchema(java.util.Map<String, java.util.Map<String, Object>> chatScheduleMessageSuccessSchema) {
        this.chatScheduleMessageSuccessSchema = chatScheduleMessageSuccessSchema;
        return this;
    }
    
    public ChatScheduleMessageResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
