/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ChatDeleteScheduledMessageApplicationJSON {
    /**
     * Pass true to delete the message as the authed user with `chat:write:user` scope. [Bot users](/bot-users) in this context are considered authed users. If unused or false, the message will be deleted with `chat:write:bot` scope.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("as_user")
    public Boolean asUser;

    public ChatDeleteScheduledMessageApplicationJSON withAsUser(Boolean asUser) {
        this.asUser = asUser;
        return this;
    }
    
    /**
     * The channel the scheduled_message is posting to
     */
    @JsonProperty("channel")
    public String channel;

    public ChatDeleteScheduledMessageApplicationJSON withChannel(String channel) {
        this.channel = channel;
        return this;
    }
    
    /**
     * `scheduled_message_id` returned from call to chat.scheduleMessage
     */
    @JsonProperty("scheduled_message_id")
    public String scheduledMessageId;

    public ChatDeleteScheduledMessageApplicationJSON withScheduledMessageId(String scheduledMessageId) {
        this.scheduledMessageId = scheduledMessageId;
        return this;
    }
    
    public ChatDeleteScheduledMessageApplicationJSON(@JsonProperty("channel") String channel, @JsonProperty("scheduled_message_id") String scheduledMessageId) {
        this.channel = channel;
        this.scheduledMessageId = scheduledMessageId;
  }
}
