/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ConversationsRenameApplicationJSON {
    /**
     * ID of conversation to rename
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("channel")
    public String channel;
    public ConversationsRenameApplicationJSON withChannel(String channel) {
        this.channel = channel;
        return this;
    }
    
    /**
     * New name for conversation.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;
    public ConversationsRenameApplicationJSON withName(String name) {
        this.name = name;
        return this;
    }
    
    public ConversationsRenameApplicationJSON(){}
}
