/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class ConversationsSetTopicRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public ConversationsSetTopicApplicationJSON requestBody;
    public ConversationsSetTopicRequest withRequestBody(ConversationsSetTopicApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `conversations:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;
    public ConversationsSetTopicRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public ConversationsSetTopicRequest(){}
}
