/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ConversationsMembersResponse {
    
    public String contentType;
    public ConversationsMembersResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public ConversationsMembersResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public ConversationsMembersResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response when an invalid cursor is provided
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> conversationsMembersErrorSchema;
    public ConversationsMembersResponse withConversationsMembersErrorSchema(java.util.Map<String, java.util.Map<String, Object>> conversationsMembersErrorSchema) {
        this.conversationsMembersErrorSchema = conversationsMembersErrorSchema;
        return this;
    }
    
    /**
     * Typical paginated success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> conversationsMembersSuccessSchema;
    public ConversationsMembersResponse withConversationsMembersSuccessSchema(java.util.Map<String, java.util.Map<String, Object>> conversationsMembersSuccessSchema) {
        this.conversationsMembersSuccessSchema = conversationsMembersSuccessSchema;
        return this;
    }
    
    public ConversationsMembersResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
