/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ConversationsSetTopicResponse {
    
    public String contentType;
    public ConversationsSetTopicResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public ConversationsSetTopicResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public ConversationsSetTopicResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> conversationsSetTopicErrorSchema;
    public ConversationsSetTopicResponse withConversationsSetTopicErrorSchema(java.util.Map<String, java.util.Map<String, Object>> conversationsSetTopicErrorSchema) {
        this.conversationsSetTopicErrorSchema = conversationsSetTopicErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> conversationsSetTopicSuccessSchema;
    public ConversationsSetTopicResponse withConversationsSetTopicSuccessSchema(java.util.Map<String, java.util.Map<String, Object>> conversationsSetTopicSuccessSchema) {
        this.conversationsSetTopicSuccessSchema = conversationsSetTopicSuccessSchema;
        return this;
    }
    
    public ConversationsSetTopicResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
