/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ConversationsSetPurposeResponse {
    
    public String contentType;
    public ConversationsSetPurposeResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public ConversationsSetPurposeResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public ConversationsSetPurposeResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> conversationsSetPurposeErrorSchema;
    public ConversationsSetPurposeResponse withConversationsSetPurposeErrorSchema(java.util.Map<String, java.util.Map<String, Object>> conversationsSetPurposeErrorSchema) {
        this.conversationsSetPurposeErrorSchema = conversationsSetPurposeErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> conversationsSetPurposeSuccessSchema;
    public ConversationsSetPurposeResponse withConversationsSetPurposeSuccessSchema(java.util.Map<String, java.util.Map<String, Object>> conversationsSetPurposeSuccessSchema) {
        this.conversationsSetPurposeSuccessSchema = conversationsSetPurposeSuccessSchema;
        return this;
    }
    
    public ConversationsSetPurposeResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
