/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ConversationsCreateApplicationJSON {
    /**
     * Create a private channel instead of a public one
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_private")
    public Boolean isPrivate;
    public ConversationsCreateApplicationJSON withIsPrivate(Boolean isPrivate) {
        this.isPrivate = isPrivate;
        return this;
    }
    
    /**
     * Name of the public or private channel to create
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;
    public ConversationsCreateApplicationJSON withName(String name) {
        this.name = name;
        return this;
    }
    
    public ConversationsCreateApplicationJSON(){}
}
