/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ConversationsListResponse {
    
    public String contentType;

    public ConversationsListResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public ConversationsListResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ConversationsListResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> conversationsListErrorSchema;

    public ConversationsListResponse withConversationsListErrorSchema(java.util.Map<String, java.util.Map<String, Object>> conversationsListErrorSchema) {
        this.conversationsListErrorSchema = conversationsListErrorSchema;
        return this;
    }
    
    /**
     * Typical success response with only public channels
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> conversationsListSuccessSchema;

    public ConversationsListResponse withConversationsListSuccessSchema(java.util.Map<String, java.util.Map<String, Object>> conversationsListSuccessSchema) {
        this.conversationsListSuccessSchema = conversationsListSuccessSchema;
        return this;
    }
    
    public ConversationsListResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
