/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ConversationsKickApplicationJSON {
    /**
     * ID of conversation to remove user from.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("channel")
    public String channel;

    public ConversationsKickApplicationJSON withChannel(String channel) {
        this.channel = channel;
        return this;
    }
    
    /**
     * User ID to be removed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("user")
    public String user;

    public ConversationsKickApplicationJSON withUser(String user) {
        this.user = user;
        return this;
    }
    
    public ConversationsKickApplicationJSON(){}
}
