/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ConversationsJoinResponse {
    
    public String contentType;

    public ConversationsJoinResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public ConversationsJoinResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ConversationsJoinResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response if the conversation is archived and cannot be joined
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> conversationsJoinErrorSchema;

    public ConversationsJoinResponse withConversationsJoinErrorSchema(java.util.Map<String, java.util.Map<String, Object>> conversationsJoinErrorSchema) {
        this.conversationsJoinErrorSchema = conversationsJoinErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> conversationsJoinSuccessSchema;

    public ConversationsJoinResponse withConversationsJoinSuccessSchema(java.util.Map<String, java.util.Map<String, Object>> conversationsJoinSuccessSchema) {
        this.conversationsJoinSuccessSchema = conversationsJoinSuccessSchema;
        return this;
    }
    
    public ConversationsJoinResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
