/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ConversationsCloseResponse {
    
    public String contentType;

    public ConversationsCloseResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public ConversationsCloseResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ConversationsCloseResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> conversationsCloseErrorSchema;

    public ConversationsCloseResponse withConversationsCloseErrorSchema(java.util.Map<String, java.util.Map<String, Object>> conversationsCloseErrorSchema) {
        this.conversationsCloseErrorSchema = conversationsCloseErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> conversationsCloseSuccessSchema;

    public ConversationsCloseResponse withConversationsCloseSuccessSchema(java.util.Map<String, java.util.Map<String, Object>> conversationsCloseSuccessSchema) {
        this.conversationsCloseSuccessSchema = conversationsCloseSuccessSchema;
        return this;
    }
    
    public ConversationsCloseResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
