/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class ConversationsMarkRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public ConversationsMarkApplicationJSON requestBody;

    public ConversationsMarkRequest withRequestBody(ConversationsMarkApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `conversations:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;

    public ConversationsMarkRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public ConversationsMarkRequest(){}
}
