/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class ConversationsJoinRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public ConversationsJoinApplicationJSON requestBody;
    public ConversationsJoinRequest withRequestBody(ConversationsJoinApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `channels:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;
    public ConversationsJoinRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public ConversationsJoinRequest(){}
}
