/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class ConversationsRenameRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public ConversationsRenameApplicationJSON requestBody;

    public ConversationsRenameRequest withRequestBody(ConversationsRenameApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `conversations:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;

    public ConversationsRenameRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public ConversationsRenameRequest(){}
}
