/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class DialogOpenRequest {
    /**
     * The dialog definition. This must be a JSON-encoded string.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=dialog")
    public String dialog;

    public DialogOpenRequest withDialog(String dialog) {
        this.dialog = dialog;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `none`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;

    public DialogOpenRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    /**
     * Exchange a trigger to post to the user.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=trigger_id")
    public String triggerId;

    public DialogOpenRequest withTriggerId(String triggerId) {
        this.triggerId = triggerId;
        return this;
    }
    
    public DialogOpenRequest(@JsonProperty("dialog") String dialog, @JsonProperty("token") String token, @JsonProperty("trigger_id") String triggerId) {
        this.dialog = dialog;
        this.token = token;
        this.triggerId = triggerId;
  }
}
