/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class DndEndSnoozeResponse {
    
    public String contentType;

    public DndEndSnoozeResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public DndEndSnoozeResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public DndEndSnoozeResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> dndEndSnoozeErrorSchema;

    public DndEndSnoozeResponse withDndEndSnoozeErrorSchema(java.util.Map<String, java.util.Map<String, Object>> dndEndSnoozeErrorSchema) {
        this.dndEndSnoozeErrorSchema = dndEndSnoozeErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> dndEndSnoozeSchema;

    public DndEndSnoozeResponse withDndEndSnoozeSchema(java.util.Map<String, java.util.Map<String, Object>> dndEndSnoozeSchema) {
        this.dndEndSnoozeSchema = dndEndSnoozeSchema;
        return this;
    }
    
    public DndEndSnoozeResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
