/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class DndInfoResponse {
    
    public String contentType;

    public DndInfoResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public DndInfoResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public DndInfoResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> dndInfoErrorSchema;

    public DndInfoResponse withDndInfoErrorSchema(java.util.Map<String, java.util.Map<String, Object>> dndInfoErrorSchema) {
        this.dndInfoErrorSchema = dndInfoErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> dndInfoSchema;

    public DndInfoResponse withDndInfoSchema(java.util.Map<String, java.util.Map<String, Object>> dndInfoSchema) {
        this.dndInfoSchema = dndInfoSchema;
        return this;
    }
    
    public DndInfoResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
