/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class DndTeamInfoRequest {
    /**
     * Authentication token. Requires scope: `dnd:read`
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=token")
    public String token;
    public DndTeamInfoRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    /**
     * Comma-separated list of users to fetch Do Not Disturb status for
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=users")
    public String users;
    public DndTeamInfoRequest withUsers(String users) {
        this.users = users;
        return this;
    }
    
    public DndTeamInfoRequest(){}
}
