/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class EmojiListRequest {
    /**
     * Authentication token. Requires scope: `emoji:read`
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=token")
    public String token;
    public EmojiListRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public EmojiListRequest(@JsonProperty("token") String token) {
        this.token = token;
  }
}
