/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class FilesSharedPublicURLResponse {
    
    public String contentType;
    public FilesSharedPublicURLResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public FilesSharedPublicURLResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public FilesSharedPublicURLResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> filesSharedPublicURLErrorSchema;
    public FilesSharedPublicURLResponse withFilesSharedPublicURLErrorSchema(java.util.Map<String, java.util.Map<String, Object>> filesSharedPublicURLErrorSchema) {
        this.filesSharedPublicURLErrorSchema = filesSharedPublicURLErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> filesSharedPublicURLSchema;
    public FilesSharedPublicURLResponse withFilesSharedPublicURLSchema(java.util.Map<String, java.util.Map<String, Object>> filesSharedPublicURLSchema) {
        this.filesSharedPublicURLSchema = filesSharedPublicURLSchema;
        return this;
    }
    
    public FilesSharedPublicURLResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
