/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class FilesRemoteAddRequestBody {
    /**
     * Creator defined GUID for the file.
     */
    @SpeakeasyMetadata("form:name=external_id")
    public String externalId;

    public FilesRemoteAddRequestBody withExternalId(String externalId) {
        this.externalId = externalId;
        return this;
    }
    
    /**
     * URL of the remote file.
     */
    @SpeakeasyMetadata("form:name=external_url")
    public String externalUrl;

    public FilesRemoteAddRequestBody withExternalUrl(String externalUrl) {
        this.externalUrl = externalUrl;
        return this;
    }
    
    /**
     * type of file
     */
    @SpeakeasyMetadata("form:name=filetype")
    public String filetype;

    public FilesRemoteAddRequestBody withFiletype(String filetype) {
        this.filetype = filetype;
        return this;
    }
    
    /**
     * A text file (txt, pdf, doc, etc.) containing textual search terms that are used to improve discovery of the remote file.
     */
    @SpeakeasyMetadata("form:name=indexable_file_contents")
    public String indexableFileContents;

    public FilesRemoteAddRequestBody withIndexableFileContents(String indexableFileContents) {
        this.indexableFileContents = indexableFileContents;
        return this;
    }
    
    /**
     * Preview of the document via `multipart/form-data`.
     */
    @SpeakeasyMetadata("form:name=preview_image")
    public String previewImage;

    public FilesRemoteAddRequestBody withPreviewImage(String previewImage) {
        this.previewImage = previewImage;
        return this;
    }
    
    /**
     * Title of the file being shared.
     */
    @SpeakeasyMetadata("form:name=title")
    public String title;

    public FilesRemoteAddRequestBody withTitle(String title) {
        this.title = title;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `remote_files:write`
     */
    @SpeakeasyMetadata("form:name=token")
    public String token;

    public FilesRemoteAddRequestBody withToken(String token) {
        this.token = token;
        return this;
    }
    
    public FilesRemoteAddRequestBody(){}
}
