/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class FilesRemoteInfoRequest {
    /**
     * Creator defined GUID for the file.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=external_id")
    public String externalId;

    public FilesRemoteInfoRequest withExternalId(String externalId) {
        this.externalId = externalId;
        return this;
    }
    
    /**
     * Specify a file by providing its ID.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=file")
    public String file;

    public FilesRemoteInfoRequest withFile(String file) {
        this.file = file;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `remote_files:read`
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=token")
    public String token;

    public FilesRemoteInfoRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public FilesRemoteInfoRequest(){}
}
