/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class MigrationExchangeResponse {
    
    public String contentType;
    public MigrationExchangeResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public MigrationExchangeResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public MigrationExchangeResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response when there are no mappings to provide
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> migrationExchangeErrorSchema;
    public MigrationExchangeResponse withMigrationExchangeErrorSchema(java.util.Map<String, java.util.Map<String, Object>> migrationExchangeErrorSchema) {
        this.migrationExchangeErrorSchema = migrationExchangeErrorSchema;
        return this;
    }
    
    /**
     * Typical success response when mappings exist for the specified user IDs
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> migrationExchangeSuccessSchema;
    public MigrationExchangeResponse withMigrationExchangeSuccessSchema(java.util.Map<String, java.util.Map<String, Object>> migrationExchangeSuccessSchema) {
        this.migrationExchangeSuccessSchema = migrationExchangeSuccessSchema;
        return this;
    }
    
    public MigrationExchangeResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
