/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class PinsRemoveRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public PinsRemoveApplicationJSON requestBody;
    public PinsRemoveRequest withRequestBody(PinsRemoveApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `pins:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;
    public PinsRemoveRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public PinsRemoveRequest(@JsonProperty("RequestBody") PinsRemoveApplicationJSON requestBody, @JsonProperty("token") String token) {
        this.requestBody = requestBody;
        this.token = token;
  }
}
