/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class PinsAddResponse {
    
    public String contentType;

    public PinsAddResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public PinsAddResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PinsAddResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> pinsAddErrorSchema;

    public PinsAddResponse withPinsAddErrorSchema(java.util.Map<String, java.util.Map<String, Object>> pinsAddErrorSchema) {
        this.pinsAddErrorSchema = pinsAddErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> pinsAddSchema;

    public PinsAddResponse withPinsAddSchema(java.util.Map<String, java.util.Map<String, Object>> pinsAddSchema) {
        this.pinsAddSchema = pinsAddSchema;
        return this;
    }
    
    public PinsAddResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
