/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class PinsAddRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public PinsAddApplicationJSON requestBody;
    public PinsAddRequest withRequestBody(PinsAddApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `pins:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;
    public PinsAddRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public PinsAddRequest(@JsonProperty("RequestBody") PinsAddApplicationJSON requestBody, @JsonProperty("token") String token) {
        this.requestBody = requestBody;
        this.token = token;
  }
}
