/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ReactionsRemoveApplicationJSON {
    /**
     * Channel where the message to remove reaction from was posted.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("channel")
    public String channel;
    public ReactionsRemoveApplicationJSON withChannel(String channel) {
        this.channel = channel;
        return this;
    }
    
    /**
     * File to remove reaction from.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("file")
    public String file;
    public ReactionsRemoveApplicationJSON withFile(String file) {
        this.file = file;
        return this;
    }
    
    /**
     * File comment to remove reaction from.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("file_comment")
    public String fileComment;
    public ReactionsRemoveApplicationJSON withFileComment(String fileComment) {
        this.fileComment = fileComment;
        return this;
    }
    
    /**
     * Reaction (emoji) name.
     */
    @JsonProperty("name")
    public String name;
    public ReactionsRemoveApplicationJSON withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * Timestamp of the message to remove reaction from.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("timestamp")
    public String timestamp;
    public ReactionsRemoveApplicationJSON withTimestamp(String timestamp) {
        this.timestamp = timestamp;
        return this;
    }
    
    public ReactionsRemoveApplicationJSON(@JsonProperty("name") String name) {
        this.name = name;
  }
}
