/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ReactionsAddApplicationJSON {
    /**
     * Channel where the message to add reaction to was posted.
     */
    @JsonProperty("channel")
    public String channel;

    public ReactionsAddApplicationJSON withChannel(String channel) {
        this.channel = channel;
        return this;
    }
    
    /**
     * Reaction (emoji) name.
     */
    @JsonProperty("name")
    public String name;

    public ReactionsAddApplicationJSON withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * Timestamp of the message to add reaction to.
     */
    @JsonProperty("timestamp")
    public String timestamp;

    public ReactionsAddApplicationJSON withTimestamp(String timestamp) {
        this.timestamp = timestamp;
        return this;
    }
    
    public ReactionsAddApplicationJSON(@JsonProperty("channel") String channel, @JsonProperty("name") String name, @JsonProperty("timestamp") String timestamp) {
        this.channel = channel;
        this.name = name;
        this.timestamp = timestamp;
  }
}
