/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class ReactionsListRequest {
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=count")
    public Long count;
    public ReactionsListRequest withCount(Long count) {
        this.count = count;
        return this;
    }
    
    /**
     * Parameter for pagination. Set `cursor` equal to the `next_cursor` attribute returned by the previous request's `response_metadata`. This parameter is optional, but pagination is mandatory: the default value simply fetches the first "page" of the collection. See [pagination](/docs/pagination) for more details.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=cursor")
    public String cursor;
    public ReactionsListRequest withCursor(String cursor) {
        this.cursor = cursor;
        return this;
    }
    
    /**
     * If true always return the complete reaction list.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=full")
    public Boolean full;
    public ReactionsListRequest withFull(Boolean full) {
        this.full = full;
        return this;
    }
    
    /**
     * The maximum number of items to return. Fewer than the requested number of items may be returned, even if the end of the list hasn't been reached.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")
    public Long limit;
    public ReactionsListRequest withLimit(Long limit) {
        this.limit = limit;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page")
    public Long page;
    public ReactionsListRequest withPage(Long page) {
        this.page = page;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `reactions:read`
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=token")
    public String token;
    public ReactionsListRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    /**
     * Show reactions made by this user. Defaults to the authed user.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=user")
    public String user;
    public ReactionsListRequest withUser(String user) {
        this.user = user;
        return this;
    }
    
    public ReactionsListRequest(@JsonProperty("token") String token) {
        this.token = token;
  }
}
