/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class ReactionsAddRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public ReactionsAddApplicationJSON requestBody;

    public ReactionsAddRequest withRequestBody(ReactionsAddApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `reactions:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;

    public ReactionsAddRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public ReactionsAddRequest(@JsonProperty("RequestBody") ReactionsAddApplicationJSON requestBody, @JsonProperty("token") String token) {
        this.requestBody = requestBody;
        this.token = token;
  }
}
