/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class ReactionsGetRequest {
    /**
     * Channel where the message to get reactions for was posted.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=channel")
    public String channel;
    public ReactionsGetRequest withChannel(String channel) {
        this.channel = channel;
        return this;
    }
    
    /**
     * File to get reactions for.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=file")
    public String file;
    public ReactionsGetRequest withFile(String file) {
        this.file = file;
        return this;
    }
    
    /**
     * File comment to get reactions for.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=file_comment")
    public String fileComment;
    public ReactionsGetRequest withFileComment(String fileComment) {
        this.fileComment = fileComment;
        return this;
    }
    
    /**
     * If true always return the complete reaction list.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=full")
    public Boolean full;
    public ReactionsGetRequest withFull(Boolean full) {
        this.full = full;
        return this;
    }
    
    /**
     * Timestamp of the message to get reactions for.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=timestamp")
    public String timestamp;
    public ReactionsGetRequest withTimestamp(String timestamp) {
        this.timestamp = timestamp;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `reactions:read`
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=token")
    public String token;
    public ReactionsGetRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public ReactionsGetRequest(@JsonProperty("token") String token) {
        this.token = token;
  }
}
