/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class RemindersAddApplicationJSON {
    /**
     * The content of the reminder
     */
    @JsonProperty("text")
    public String text;
    public RemindersAddApplicationJSON withText(String text) {
        this.text = text;
        return this;
    }
    
    /**
     * When this reminder should happen: the Unix timestamp (up to five years from now), the number of seconds until the reminder (if within 24 hours), or a natural language description (Ex. "in 15 minutes," or "every Thursday")
     */
    @JsonProperty("time")
    public String time;
    public RemindersAddApplicationJSON withTime(String time) {
        this.time = time;
        return this;
    }
    
    /**
     * The user who will receive the reminder. If no user is specified, the reminder will go to user who created it.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("user")
    public String user;
    public RemindersAddApplicationJSON withUser(String user) {
        this.user = user;
        return this;
    }
    
    public RemindersAddApplicationJSON(@JsonProperty("text") String text, @JsonProperty("time") String time) {
        this.text = text;
        this.time = time;
  }
}
