/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class RemindersInfoResponse {
    
    public String contentType;
    public RemindersInfoResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public RemindersInfoResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public RemindersInfoResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> remindersInfoErrorSchema;
    public RemindersInfoResponse withRemindersInfoErrorSchema(java.util.Map<String, java.util.Map<String, Object>> remindersInfoErrorSchema) {
        this.remindersInfoErrorSchema = remindersInfoErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> remindersInfoSchema;
    public RemindersInfoResponse withRemindersInfoSchema(java.util.Map<String, java.util.Map<String, Object>> remindersInfoSchema) {
        this.remindersInfoSchema = remindersInfoSchema;
        return this;
    }
    
    public RemindersInfoResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
