/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class RemindersDeleteRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public RemindersDeleteApplicationJSON requestBody;
    public RemindersDeleteRequest withRequestBody(RemindersDeleteApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `reminders:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;
    public RemindersDeleteRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public RemindersDeleteRequest(){}
}
