/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class RemindersInfoRequest {
    /**
     * The ID of the reminder
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=reminder")
    public String reminder;
    public RemindersInfoRequest withReminder(String reminder) {
        this.reminder = reminder;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `reminders:read`
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=token")
    public String token;
    public RemindersInfoRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public RemindersInfoRequest(){}
}
