/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class RemindersAddResponse {
    
    public String contentType;
    public RemindersAddResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public RemindersAddResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public RemindersAddResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> remindersAddErrorSchema;
    public RemindersAddResponse withRemindersAddErrorSchema(java.util.Map<String, java.util.Map<String, Object>> remindersAddErrorSchema) {
        this.remindersAddErrorSchema = remindersAddErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> remindersAddSchema;
    public RemindersAddResponse withRemindersAddSchema(java.util.Map<String, java.util.Map<String, Object>> remindersAddSchema) {
        this.remindersAddSchema = remindersAddSchema;
        return this;
    }
    
    public RemindersAddResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
