/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class RtmConnectResponse {
    
    public String contentType;
    public RtmConnectResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public RtmConnectResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public RtmConnectResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> rtmConnectErrorSchema;
    public RtmConnectResponse withRtmConnectErrorSchema(java.util.Map<String, java.util.Map<String, Object>> rtmConnectErrorSchema) {
        this.rtmConnectErrorSchema = rtmConnectErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> rtmConnectSchema;
    public RtmConnectResponse withRtmConnectSchema(java.util.Map<String, java.util.Map<String, Object>> rtmConnectSchema) {
        this.rtmConnectSchema = rtmConnectSchema;
        return this;
    }
    
    public RtmConnectResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
