/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class StarsAddRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public StarsAddApplicationJSON requestBody;

    public StarsAddRequest withRequestBody(StarsAddApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `stars:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;

    public StarsAddRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public StarsAddRequest(@JsonProperty("token") String token) {
        this.token = token;
  }
}
