/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class StarsAddApplicationJSON {
    /**
     * Channel to add star to, or channel where the message to add star to was posted (used with `timestamp`).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("channel")
    public String channel;

    public StarsAddApplicationJSON withChannel(String channel) {
        this.channel = channel;
        return this;
    }
    
    /**
     * File to add star to.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("file")
    public String file;

    public StarsAddApplicationJSON withFile(String file) {
        this.file = file;
        return this;
    }
    
    /**
     * File comment to add star to.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("file_comment")
    public String fileComment;

    public StarsAddApplicationJSON withFileComment(String fileComment) {
        this.fileComment = fileComment;
        return this;
    }
    
    /**
     * Timestamp of the message to add star to.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("timestamp")
    public String timestamp;

    public StarsAddApplicationJSON withTimestamp(String timestamp) {
        this.timestamp = timestamp;
        return this;
    }
    
    public StarsAddApplicationJSON(){}
}
