/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class StarsAddResponse {
    
    public String contentType;
    public StarsAddResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public StarsAddResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public StarsAddResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> starsAddErrorSchema;
    public StarsAddResponse withStarsAddErrorSchema(java.util.Map<String, java.util.Map<String, Object>> starsAddErrorSchema) {
        this.starsAddErrorSchema = starsAddErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> starsAddSchema;
    public StarsAddResponse withStarsAddSchema(java.util.Map<String, java.util.Map<String, Object>> starsAddSchema) {
        this.starsAddSchema = starsAddSchema;
        return this;
    }
    
    public StarsAddResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
