/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class TeamIntegrationLogsRequest {
    /**
     * Filter logs to this Slack app. Defaults to all logs.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=app_id")
    public String appId;

    public TeamIntegrationLogsRequest withAppId(String appId) {
        this.appId = appId;
        return this;
    }
    
    /**
     * Filter logs with this change type. Defaults to all logs.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=change_type")
    public String changeType;

    public TeamIntegrationLogsRequest withChangeType(String changeType) {
        this.changeType = changeType;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=count")
    public String count;

    public TeamIntegrationLogsRequest withCount(String count) {
        this.count = count;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page")
    public String page;

    public TeamIntegrationLogsRequest withPage(String page) {
        this.page = page;
        return this;
    }
    
    /**
     * Filter logs to this service. Defaults to all logs.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=service_id")
    public String serviceId;

    public TeamIntegrationLogsRequest withServiceId(String serviceId) {
        this.serviceId = serviceId;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `admin`
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=token")
    public String token;

    public TeamIntegrationLogsRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    /**
     * Filter logs generated by this user\u2019s actions. Defaults to all logs.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=user")
    public String user;

    public TeamIntegrationLogsRequest withUser(String user) {
        this.user = user;
        return this;
    }
    
    public TeamIntegrationLogsRequest(@JsonProperty("token") String token) {
        this.token = token;
  }
}
