/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class TeamInfoResponse {
    
    public String contentType;
    public TeamInfoResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public TeamInfoResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public TeamInfoResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> teamInfoErrorSchema;
    public TeamInfoResponse withTeamInfoErrorSchema(java.util.Map<String, java.util.Map<String, Object>> teamInfoErrorSchema) {
        this.teamInfoErrorSchema = teamInfoErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> teamInfoSchema;
    public TeamInfoResponse withTeamInfoSchema(java.util.Map<String, java.util.Map<String, Object>> teamInfoSchema) {
        this.teamInfoSchema = teamInfoSchema;
        return this;
    }
    
    public TeamInfoResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
