/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class UsersGetPresenceResponse {
    /**
     * When requesting information for a different user, this method just returns the current presence (either `active` or `away`).
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> apiMethodUsersGetPresence;
    public UsersGetPresenceResponse withAPIMethodUsersGetPresence(java.util.Map<String, java.util.Map<String, Object>> apiMethodUsersGetPresence) {
        this.apiMethodUsersGetPresence = apiMethodUsersGetPresence;
        return this;
    }
    
    
    public String contentType;
    public UsersGetPresenceResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public UsersGetPresenceResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public UsersGetPresenceResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> usersCountsErrorSchema;
    public UsersGetPresenceResponse withUsersCountsErrorSchema(java.util.Map<String, java.util.Map<String, Object>> usersCountsErrorSchema) {
        this.usersCountsErrorSchema = usersCountsErrorSchema;
        return this;
    }
    
    public UsersGetPresenceResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
