/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class UsersSetActiveResponse {
    
    public String contentType;
    public UsersSetActiveResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public UsersSetActiveResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public UsersSetActiveResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> usersSetActiveErrorSchema;
    public UsersSetActiveResponse withUsersSetActiveErrorSchema(java.util.Map<String, java.util.Map<String, Object>> usersSetActiveErrorSchema) {
        this.usersSetActiveErrorSchema = usersSetActiveErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> usersSetActiveSchema;
    public UsersSetActiveResponse withUsersSetActiveSchema(java.util.Map<String, java.util.Map<String, Object>> usersSetActiveSchema) {
        this.usersSetActiveSchema = usersSetActiveSchema;
        return this;
    }
    
    public UsersSetActiveResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
