/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class UsersProfileGetResponse {
    
    public String contentType;

    public UsersProfileGetResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public UsersProfileGetResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public UsersProfileGetResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> usersProfileGetErrorSchema;

    public UsersProfileGetResponse withUsersProfileGetErrorSchema(java.util.Map<String, java.util.Map<String, Object>> usersProfileGetErrorSchema) {
        this.usersProfileGetErrorSchema = usersProfileGetErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> usersProfileGetSchema;

    public UsersProfileGetResponse withUsersProfileGetSchema(java.util.Map<String, java.util.Map<String, Object>> usersProfileGetSchema) {
        this.usersProfileGetSchema = usersProfileGetSchema;
        return this;
    }
    
    public UsersProfileGetResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
