/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class UsersProfileGetRequest {
    /**
     * Include labels for each ID in custom profile fields
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=include_labels")
    public Boolean includeLabels;
    public UsersProfileGetRequest withIncludeLabels(Boolean includeLabels) {
        this.includeLabels = includeLabels;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `users.profile:read`
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=token")
    public String token;
    public UsersProfileGetRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    /**
     * User to retrieve profile info for
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=user")
    public String user;
    public UsersProfileGetRequest withUser(String user) {
        this.user = user;
        return this;
    }
    
    public UsersProfileGetRequest(@JsonProperty("token") String token) {
        this.token = token;
  }
}
