/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class UsersProfileSetResponse {
    
    public String contentType;

    public UsersProfileSetResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public UsersProfileSetResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public UsersProfileSetResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> usersProfileSetErrorSchema;

    public UsersProfileSetResponse withUsersProfileSetErrorSchema(java.util.Map<String, java.util.Map<String, Object>> usersProfileSetErrorSchema) {
        this.usersProfileSetErrorSchema = usersProfileSetErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> usersProfileSetSchema;

    public UsersProfileSetResponse withUsersProfileSetSchema(java.util.Map<String, java.util.Map<String, Object>> usersProfileSetSchema) {
        this.usersProfileSetSchema = usersProfileSetSchema;
        return this;
    }
    
    public UsersProfileSetResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
