/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class UsersInfoResponse {
    
    public String contentType;
    public UsersInfoResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public UsersInfoResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public UsersInfoResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> usersInfoErrorSchema;
    public UsersInfoResponse withUsersInfoErrorSchema(java.util.Map<String, java.util.Map<String, Object>> usersInfoErrorSchema) {
        this.usersInfoErrorSchema = usersInfoErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> usersInfoSuccessSchema;
    public UsersInfoResponse withUsersInfoSuccessSchema(java.util.Map<String, java.util.Map<String, Object>> usersInfoSuccessSchema) {
        this.usersInfoSuccessSchema = usersInfoSuccessSchema;
        return this;
    }
    
    public UsersInfoResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
