/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class UsergroupsCreateRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public UsergroupsCreateApplicationJSON requestBody;

    public UsergroupsCreateRequest withRequestBody(UsergroupsCreateApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `usergroups:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;

    public UsergroupsCreateRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public UsergroupsCreateRequest(@JsonProperty("RequestBody") UsergroupsCreateApplicationJSON requestBody, @JsonProperty("token") String token) {
        this.requestBody = requestBody;
        this.token = token;
  }
}
