/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class UsergroupsUsersUpdateRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public UsergroupsUsersUpdateApplicationJSON requestBody;
    public UsergroupsUsersUpdateRequest withRequestBody(UsergroupsUsersUpdateApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `usergroups:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;
    public UsergroupsUsersUpdateRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public UsergroupsUsersUpdateRequest(@JsonProperty("RequestBody") UsergroupsUsersUpdateApplicationJSON requestBody, @JsonProperty("token") String token) {
        this.requestBody = requestBody;
        this.token = token;
  }
}
