/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class UsersProfileSetRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public UsersProfileSetApplicationJSON requestBody;

    public UsersProfileSetRequest withRequestBody(UsersProfileSetApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `users.profile:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;

    public UsersProfileSetRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public UsersProfileSetRequest(@JsonProperty("token") String token) {
        this.token = token;
  }
}
