/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class UsersDeletePhotoResponse {
    
    public String contentType;

    public UsersDeletePhotoResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public UsersDeletePhotoResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public UsersDeletePhotoResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> usersDeletePhotoErrorSchema;

    public UsersDeletePhotoResponse withUsersDeletePhotoErrorSchema(java.util.Map<String, java.util.Map<String, Object>> usersDeletePhotoErrorSchema) {
        this.usersDeletePhotoErrorSchema = usersDeletePhotoErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> usersDeletePhotoSchema;

    public UsersDeletePhotoResponse withUsersDeletePhotoSchema(java.util.Map<String, java.util.Map<String, Object>> usersDeletePhotoSchema) {
        this.usersDeletePhotoSchema = usersDeletePhotoSchema;
        return this;
    }
    
    public UsersDeletePhotoResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
