/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class UsersSetPresenceRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public UsersSetPresenceApplicationJSON requestBody;

    public UsersSetPresenceRequest withRequestBody(UsersSetPresenceApplicationJSON requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `users:write`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;

    public UsersSetPresenceRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    public UsersSetPresenceRequest(@JsonProperty("RequestBody") UsersSetPresenceApplicationJSON requestBody, @JsonProperty("token") String token) {
        this.requestBody = requestBody;
        this.token = token;
  }
}
