/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class UsersProfileSetApplicationJSON {
    /**
     * Name of a single key to set. Usable only if `profile` is not passed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;
    public UsersProfileSetApplicationJSON withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * Collection of key:value pairs presented as a URL-encoded JSON hash. At most 50 fields may be set. Each field name is limited to 255 characters.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("profile")
    public String profile;
    public UsersProfileSetApplicationJSON withProfile(String profile) {
        this.profile = profile;
        return this;
    }
    
    /**
     * ID of user to change. This argument may only be specified by team admins on paid teams.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("user")
    public String user;
    public UsersProfileSetApplicationJSON withUser(String user) {
        this.user = user;
        return this;
    }
    
    /**
     * Value to set a single key to. Usable only if `profile` is not passed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("value")
    public String value;
    public UsersProfileSetApplicationJSON withValue(String value) {
        this.value = value;
        return this;
    }
    
    public UsersProfileSetApplicationJSON(){}
}
