/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class UsersInfoRequest {
    /**
     * Set this to `true` to receive the locale for this user. Defaults to `false`
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=include_locale")
    public Boolean includeLocale;
    public UsersInfoRequest withIncludeLocale(Boolean includeLocale) {
        this.includeLocale = includeLocale;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `users:read`
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=token")
    public String token;
    public UsersInfoRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    /**
     * User to get info on
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=user")
    public String user;
    public UsersInfoRequest withUser(String user) {
        this.user = user;
        return this;
    }
    
    public UsersInfoRequest(@JsonProperty("token") String token) {
        this.token = token;
  }
}
