/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class UsersSetPresenceResponse {
    
    public String contentType;
    public UsersSetPresenceResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public UsersSetPresenceResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public UsersSetPresenceResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> usersSetPresenceErrorSchema;
    public UsersSetPresenceResponse withUsersSetPresenceErrorSchema(java.util.Map<String, java.util.Map<String, Object>> usersSetPresenceErrorSchema) {
        this.usersSetPresenceErrorSchema = usersSetPresenceErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> usersSetPresenceSchema;
    public UsersSetPresenceResponse withUsersSetPresenceSchema(java.util.Map<String, java.util.Map<String, Object>> usersSetPresenceSchema) {
        this.usersSetPresenceSchema = usersSetPresenceSchema;
        return this;
    }
    
    public UsersSetPresenceResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
