/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UsersSetPresenceApplicationJSON {
    /**
     * Either `auto` or `away`
     */
    @JsonProperty("presence")
    public String presence;
    public UsersSetPresenceApplicationJSON withPresence(String presence) {
        this.presence = presence;
        return this;
    }
    
    public UsersSetPresenceApplicationJSON(@JsonProperty("presence") String presence) {
        this.presence = presence;
  }
}
