/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class UsergroupsUsersUpdateApplicationJSON {
    /**
     * Include the number of users in the User Group.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("include_count")
    public Boolean includeCount;
    public UsergroupsUsersUpdateApplicationJSON withIncludeCount(Boolean includeCount) {
        this.includeCount = includeCount;
        return this;
    }
    
    /**
     * The encoded ID of the User Group to update.
     */
    @JsonProperty("usergroup")
    public String usergroup;
    public UsergroupsUsersUpdateApplicationJSON withUsergroup(String usergroup) {
        this.usergroup = usergroup;
        return this;
    }
    
    /**
     * A comma separated string of encoded user IDs that represent the entire list of users for the User Group.
     */
    @JsonProperty("users")
    public String users;
    public UsergroupsUsersUpdateApplicationJSON withUsers(String users) {
        this.users = users;
        return this;
    }
    
    public UsergroupsUsersUpdateApplicationJSON(@JsonProperty("usergroup") String usergroup, @JsonProperty("users") String users) {
        this.usergroup = usergroup;
        this.users = users;
  }
}
