/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class UsergroupsCreateResponse {
    
    public String contentType;

    public UsergroupsCreateResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public UsergroupsCreateResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public UsergroupsCreateResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Typical error response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> usergroupsCreateErrorSchema;

    public UsergroupsCreateResponse withUsergroupsCreateErrorSchema(java.util.Map<String, java.util.Map<String, Object>> usergroupsCreateErrorSchema) {
        this.usergroupsCreateErrorSchema = usergroupsCreateErrorSchema;
        return this;
    }
    
    /**
     * Typical success response
     */
    
    public java.util.Map<String, java.util.Map<String, Object>> usergroupsCreateSchema;

    public UsergroupsCreateResponse withUsergroupsCreateSchema(java.util.Map<String, java.util.Map<String, Object>> usergroupsCreateSchema) {
        this.usergroupsCreateSchema = usergroupsCreateSchema;
        return this;
    }
    
    public UsergroupsCreateResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
