/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class WorkflowsStepCompletedRequest {
    /**
     * Key-value object of outputs from your step. Keys of this object reflect the configured `key` properties of your [`outputs`](/reference/workflows/workflow_step#output) array from your `workflow_step` object.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=outputs")
    public String outputs;
    public WorkflowsStepCompletedRequest withOutputs(String outputs) {
        this.outputs = outputs;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `workflow.steps:execute`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;
    public WorkflowsStepCompletedRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    /**
     * Context identifier that maps to the correct workflow step execution.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=workflow_step_execute_id")
    public String workflowStepExecuteId;
    public WorkflowsStepCompletedRequest withWorkflowStepExecuteId(String workflowStepExecuteId) {
        this.workflowStepExecuteId = workflowStepExecuteId;
        return this;
    }
    
    public WorkflowsStepCompletedRequest(@JsonProperty("token") String token, @JsonProperty("workflow_step_execute_id") String workflowStepExecuteId) {
        this.token = token;
        this.workflowStepExecuteId = workflowStepExecuteId;
  }
}
