/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package shadowcodex.slack_spec.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import shadowcodex.slack_spec.utils.SpeakeasyMetadata;

public class WorkflowsStepFailedRequest {
    /**
     * A JSON-based object with a `message` property that should contain a human readable error message.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=error")
    public String error;

    public WorkflowsStepFailedRequest withError(String error) {
        this.error = error;
        return this;
    }
    
    /**
     * Authentication token. Requires scope: `workflow.steps:execute`
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=token")
    public String token;

    public WorkflowsStepFailedRequest withToken(String token) {
        this.token = token;
        return this;
    }
    
    /**
     * Context identifier that maps to the correct workflow step execution.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=workflow_step_execute_id")
    public String workflowStepExecuteId;

    public WorkflowsStepFailedRequest withWorkflowStepExecuteId(String workflowStepExecuteId) {
        this.workflowStepExecuteId = workflowStepExecuteId;
        return this;
    }
    
    public WorkflowsStepFailedRequest(@JsonProperty("error") String error, @JsonProperty("token") String token, @JsonProperty("workflow_step_execute_id") String workflowStepExecuteId) {
        this.error = error;
        this.token = token;
        this.workflowStepExecuteId = workflowStepExecuteId;
  }
}
